spring.application.name=conteo
server.port=9295
spring.datasource.url=jdbc:postgresql://172.16.21.12:5432/bd_eleccion_pando
spring.datasource.username=postgres
spring.datasource.password=usic2024
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=update