spring.application.name=conteo
server.port=9295
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_secreto_02
spring.datasource.username=postgres
spring.datasource.password=curso2021.
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=update